-- Cambiar campos de cantidad de INTEGER a DOUBLE PRECISION (Float)
ALTER TABLE "ArticuloNivel" ALTER COLUMN "cantidad" TYPE DOUBLE PRECISION;
ALTER TABLE "ArticuloUbicacion" ALTER COLUMN "cantidad" TYPE DOUBLE PRECISION;
ALTER TABLE "LoteEntrada" ALTER COLUMN "cantidadOriginal" TYPE DOUBLE PRECISION;
ALTER TABLE "LoteEntrada" ALTER COLUMN "cantidadDisponible" TYPE DOUBLE PRECISION;
ALTER TABLE "SalidaItem" ALTER COLUMN "cantidad" TYPE DOUBLE PRECISION;
ALTER TABLE "ApartadoItem" ALTER COLUMN "cantidad" TYPE DOUBLE PRECISION;
ALTER TABLE "Movimiento" ALTER COLUMN "cantidadMovida" TYPE DOUBLE PRECISION;
